#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""P7 §8.13.6：Step 9 的外部对照（**本仓库既有口径** + 公开文献口径 + 负结果 + 下一步）。

**在 Windows 侧跑**（`md文档/` 树在 git 仓库之外）。前置：§8.13 已由 `p7_step9_docs.py` 写入。

证据纪律：
  * 「甲」（本仓库口径）**全部由本机文件断言** ⇒ 随上游改动即失效、逼迫重写 ✓；
  * 「乙/丙」（公开文献）由检索代理下载原文摘录并附 URL，但**本机网络策略拦截、未能二次复核** ✗
    ⇒ 只用于「我们的做法是否落在领域惯例内」，**不引入任何外部数字** ✓。

用法：python3 logs_hkem/p256fold_20260928T085338Z/rtl/p7_step9_ext_docs.py [--check] [--docs-dir DIR]
"""
import argparse
import pathlib
import re
import sys

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

REPO = pathlib.Path(__file__).resolve().parents[3]
DOCS = REPO.parent / "md文档" / "p256方案20260927" / "new_contribution_2"
DOC = "08_P7_PPA与CSA决策.md"
PSR = REPO / "hw/syn/tools/dc/parse-syn-report.py"
RST = REPO / "hw/syn/tools/dc/run-syn.tcl"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--docs-dir")
    args = ap.parse_args()
    global DOCS
    if args.docs_dir:
        DOCS = pathlib.Path(args.docs_dir)
    DOCS = pathlib.Path(DOCS)

    # ---- 甲：本仓库既有口径（本机文件断言，失效即拒绝写）
    psr = PSR.read_text(encoding="utf-8", errors="replace")
    rst = RST.read_text(encoding="utf-8", errors="replace")
    for pat, what in ((r'\("net",\s*r"\^"', "power.net"), (r'\("int",', "power.int"),
                      (r'\("leak",', "power.leak"), (r'\("voltage",', "units.voltage"),
                      (r'\("capacitance",', "units.capacitance"), (r'\("time",', "units.time"),
                      (r'\("dynamic",', "units.dynamic")):
        assert re.search(pat, psr), "parse-syn-report.py 里找不到 %s ⇒ §8.13.6「甲」失效" % what
    m = re.search(r"^report_power\s+-hier -nosplit", rst, re.M)
    assert m, "run-syn.tcl 里找不到 report_power -hier -nosplit ⇒ §8.13.6「甲」失效"
    ln = rst[:m.start()].count("\n") + 1

    L = []
    L.append("#### 8.13.6 外部对照：本仓库既有口径 + 公开文献 + 三条负结果（2026-09-30）")
    L.append("")
    L.append("**甲、本仓库自己的功耗口径（本机可核 ⇒ 本节最强证据）**")
    L.append("")
    L.append("上游 OTBN 综合流程走 **Design Compiler**：`hw/syn/tools/dc/run-syn.tcl:%d` "
             "`report_power -hier -nosplit > power.rpt`；仓库自带解析器把它归成**三分量 + 单位**："
             "`power = {net, int, leak}`（`hw/syn/tools/dc/parse-syn-report.py` 的 `_extract_power`）"
             "并**单独解析** `Voltage / Capacitance / Time / Dynamic Power Units`（同文件 `_extract_units`）✓。" % ln)
    L.append("")
    L.append("⇒ 我们的 A 档（`P_sw / P_int / P_leak` 三分量 + **逐项**从 liberty 解析单位）**与仓库既有口径同构** ✓；"
             "差别**只在工具**：DC 需商业许可、本环境没有 ⇒ 用 yosys/ABC 网表 + 解析式估计。"
             "**不得**把 8.13.1 的表写成 DC/签核结果 ✗（同一纪律见 §8.4 第 1 条）。")
    L.append("")
    L.append("**乙、公开文献口径对照（只回答「我们的做法是否落在领域惯例内」；不引入任何外部数字 ✓）**")
    L.append("")
    L.append("> ⚠ 下列条目由检索代理下载 PDF 原文摘录（附 URL），但**本机网络策略拦截 ⇒ 未能二次复核** ✗"
             "⇒ 只作口径对照，**不作任何本项目数字的依据** ✓。")
    L.append("")
    L.append("| 问 | 领域惯例（出处） | 我们的对应 |")
    L.append("|---|---|---|")
    L.append("| 用什么工具 | 开源路线已足够：TCHES 2026 FrodoKEM 全程 OpenROAD（“Area, Power, and Frequency "
             "estimates are extracted from final report generated by the OpenROAD toolchain”；"
             "`tches.v2026.i3.881-907`）。商业路线：Cadence Joules（RISQ-V，`tches.v2020.i4`）、"
             "DC + PrimeTime（ePrint 2025/308） | 无商业许可 ⇒ 开源链路（§8.13.1/8.13.2）✓ |")
    L.append("| 活动率从哪来 | 主流是**仿真回标**：门级 **SAIF**→Joules（RISQ-V）、综合后仿真逐门收集→PrimeTime"
             "（ePrint 2025/308）；无仿真时用 **vectorless 默认**（OpenSTA 文档：输入默认 activity 0.1、"
             "duty 0.5） | **A 档 α=0.10 档恰为该默认值** ✓；α=0.25/0.5 是我们另加的档（见 8.13.2 对照）|")
    L.append("| 双口径并列 | CMALU（ICCAD'26，ePrint 2026/1423）同篇并列 **SAIF 口径**与 **vectorless 口径**，"
             "并明说后者是保守上界 | **与我们的 A/B 两档同构** ✓（A 档=上界、B 档=实测活动率）|")
    L.append("| 报什么粒度 | 事实标准是 `cycles + power + energy/op`（Sapphire，TCHES 2019(4) 表 7）；"
             "leakage **单独一列**（RISQ-V 表 8 的四分量） | 8.13.3 的分列 ✓；`energy/op` 见 8.13.1 表 A-2 ✓ |")
    L.append("| 条件怎么给 | 一句到底的铭牌：库 + 电压 + 频率 + 温度 + **综合阶段**（RISQ-V：10 MHz / 1.2 V / "
             "25 ℃ / UMC 65 nm / **post-synthesis**）；post-layout 非必需（Niederhagen&Pham："
             "“post-synthesis without P&R … a common choice”）| 8.13.3 表同构 ✓；我们是 post-synthesis、"
             "**无 PEX** ✓（该限制已在 8.13.4 第 3 条）|")
    L.append("| 硅测 | 片上 clock gate 隔离被测模块 + GPIO 测量窗口 + 源表（Sapphire：Keithley 2602A）| "
             "**需流片 ⇒ 本项目不可得** ✗（本仓库唯一现成采集设施是 ot-sca 的 CW310 功耗迹，"
             "用途是侧信道、不是能耗指标 ✗）|")
    L.append("")
    L.append("**丙、三条负结果（它们决定「我们不许写什么」）**")
    L.append("")
    L.append("1. **OTBN 系论文一律不报功耗/能耗**（OTBNTW S&P'25、Niederhagen&Pham TCHES 2026(2)、Etterli "
             "设计报告、SOSK23：全文只有 cycles / 面积 kGE / Fmax / time-area product，**无 mW/µJ**）"
             "⇒ **文献中不存在 OTBN 能耗基线** ⇒「比 OTBN 省 X%」**不成立** ✗；我们只能说**同口径自比** ✓。")
    L.append("2. **未找到量化 clock gating 省电比例的 PQC/ECC 论文**（Sapphire 只有定性描述）⇒ 我们只陈述"
             "「ICG=0」这一**事实** ✗，不推省电百分比 ✓。")
    L.append("3. 检索中**未出现 “PrimeTime PX”**（只有 “Prime Time”）⇒ 论文里不要写 PX ✗（若将来引用商业工具，"
             "写准确名称 ✓）。")
    L.append("")
    L.append("**丁、由本节得出的可执行改进（下一步，尚未做）**")
    L.append("")
    L.append("1. **B 档升级为工具链路径**：用 OpenSTA 官方流程 `read_vcd`（或 `read_saif`）+ "
             "`report_activity_annotation` + `report_power`（官方最小样例 `examples/power_vcd.tcl`）"
             "⇒ 直接得到**与仓库 DC 口径同构**的 net/int/leak 三分量 + 单位 ✓；SAIF 来源可用 Verilator "
             "官方选项 `--trace-saif`（RTL 级）✓。**现在这版是自研解析器**（§8.13.2），两者可互校 ✓。")
    L.append("2. **覆盖率护栏**：`report_activity_annotation` 的「已标注/未标注 pin 数」可作第二条「拒绝出数」"
             "判据（第一条 = 同 run `area.rpt` 实例数一致，§8.13.1）✓。")
    L.append("3. **双口径写法**：A 档明确声明为**上界**（vectorless），B 档为**实测活动率口径**，两列并列 ✓"
             "（CMALU 先例）；论文里同时给两口径，比只给一档更抗审 ✓。")
    L.append("")

    sec = "\n".join(L)
    p = DOCS / DOC
    assert p.exists(), ("找不到 %s\n⇒ 本脚本是 **Windows 侧工具**：`md文档/` 在 git 仓库之外（仓库的上一级）。"
                        "\n   确需在别处生成：`--docs-dir <new_contribution_2 的路径>`。" % p)
    t = p.read_text(encoding="utf-8")
    assert "### 8.13 " in t, "§8.13 尚未写入 ⇒ 先用 p7_step9_docs.py"
    assert "#### 8.13.6 " not in t, "§8.13.6 已存在"
    if not args.check:
        p.write_text(t.rstrip("\n") + "\n\n" + sec, encoding="utf-8")
    print(sec)
    print("OK" + (" (check only)" if args.check else ""))


if __name__ == "__main__":
    main()
