/*
 * Testwrapper for hkdf_sha3_256 — Hybrid KEM parameters
 * Generated by ref/hkdf_kat.py
 */

.section .text.start

.globl main
main:
    la      x2, stack_end
    addi    x2, x2, -64
    jal     x1, hkdf_extract
    jal     x1, hkdf_expand
    ecall

.data

/* ---- Stack ---- */

.balign 32
.globl stack
stack:
    .zero 512
stack_end:

/* ---- HKDF salt (32B, all zeros) ---- */

.balign 32
.globl input_salt
input_salt:
    .word 0x03020100
    .word 0x07060504
    .word 0x0b0a0908
    .word 0x0f0e0d0c
    .word 0x13121110
    .word 0x17161514
    .word 0x1b1a1918
    .word 0x1f1e1d1c

/* ---- Pre-built IKM: ss_e(32B)||ss_m(32B)||ctx(32B) = 96B（无长度前缀、无 sid） ---- */

.balign 32
.globl ikm_prebuilt
ikm_prebuilt:
    .word 0x46d7335f    /* ss_e[0:4] */
    .word 0x0a6426a3    /* ss_e[4:8] */
    .word 0x90949a73    /* ss_e[8:12] */
    .word 0x03c115ec    /* ss_e[12:16] */
    .word 0x3d9f8672    /* ss_e[16:20] */
    .word 0xe8b275e6    /* ss_e[20:24] */
    .word 0x1d274257    /* ss_e[24:28] */
    .word 0x82ebc918    /* ss_e[28:32] */
    .word 0x4aac5037    /* ss_m[0:4] */
    .word 0x2763658e    /* ss_m[4:8] */
    .word 0xfa81d1c3    /* ss_m[8:12] */
    .word 0x4b5502b0    /* ss_m[12:16] */
    .word 0x04bed2f6    /* ss_m[16:20] */
    .word 0xd528dd75    /* ss_m[20:24] */
    .word 0x9fef1bf3    /* ss_m[24:28] */
    .word 0xac865f83    /* ss_m[28:32] */
    .word 0x72627948    /* ctx[0:4]  "Hybr" */
    .word 0x454b6469    /* ctx[4:8]  "idKE" */
    .word 0x31762d4d    /* ctx[8:12]  "M-v1" */
    .word 0x6e6f632d    /* ctx[12:16]  "-con" */
    .word 0x74786574    /* ctx[16:20]  "text" */
    .word 0x3231302d    /* ctx[20:24]  "-012" */
    .word 0x36353433    /* ctx[24:28]  "3456" */
    .word 0x41393837    /* ctx[28:32]  "789A" */

/* ---- HKDF-Expand info_len (separate from IKM input_lengths) ---- */
.balign 4
.globl input_info_len
input_info_len:
    .word 16    /* info_len (16B for kInfo[16]) */

/* ---- HKDF-Expand info ---- */
.balign 32
.globl input_info
input_info:
    .word 0x04030201    /* info[0:4] */
    .word 0x08070605    /* info[4:8] */
    .word 0x0c0b0a09    /* info[8:12] */
    .word 0x100f0e0d    /* info[12:16] */


/* ---- IKM-related lengths (Extract), NOT info_len ---- */
.balign 32
.globl input_lengths
input_lengths:
    .word 32    /* ctx_len  at +0 */
    .word 32    /* okm_len  at +4 */

/* ---- HMAC work buffers ---- */

/* ---- Constants ---- */

.balign 32
.globl const_0x36
const_0x36:
    .rept 40
    .word 0x36363636
    .endr

.balign 32
.globl const_0x5c
const_0x5c:
    .rept 40
    .word 0x5c5c5c5c
    .endr

.balign 32
.globl hmac_ipad
hmac_ipad:
    .zero 160

.balign 32
.globl hmac_opad
hmac_opad:
    .zero 160

.balign 32
.globl hmac_inner
hmac_inner:
    .zero 32

.balign 32
.globl hmac_key_hashed
hmac_key_hashed:
    .zero 32

.balign 32
.globl hmac_msg
hmac_msg:
    .zero 288

/* ---- IKM construction + output ---- */

.balign 32
.globl ikm_buf
ikm_buf:
    .zero 1024

.balign 32
.globl t_buf
t_buf:
    .zero 32

.balign 32
.globl output_okm
output_okm:
    .zero 256
